[project]
authors = ["Gui Castelao <gpimenta@nrel.gov>"]
channels = ["conda-forge", "anaconda", "main"]
description = "Add a short description here"
name = "ordinanceDB"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.0.1"

[tasks]

[dependencies]
rust = ">=1.82.0,<1.83"
