[workspace]
members = [ "crates/cli","crates/ordinance"]
default-members = ["crates/ordinance"]
resolver = "2"

[workspace.package]
version = "0.0.3"
authors = [
  "Guilherme Castelão <gpimenta@nrel.gov>",
  "Paul Pinchuk <Pavlo.Pinchuk@nrel.gov>",
  ]
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.80.0"

[workspace.dependencies]
clap = { version = "4.5.21" }
csv = { version = "1.3.1" }
duckdb = { version = "1.1.1", features = ["bundled"] }
ordinance = { version = ">=0.0.3", path = "crates/ordinance" }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = { version = "1.0.133" }
tempfile = { version = "3.14.0" }
thiserror = { version = "2.0.3" }
tokio = { version = "1.42.0", features = ["rt", "macros"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "fmt"]}
tracing-appender = "0.2"
