name: Release Documentation

permissions: write-all

on:
  pull_request:
  push:
    branches: [main]
  release:
    types: [created, published]
  workflow_dispatch:

jobs:
  build_docs:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
      - name: Pull Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: prefix-dev/setup-pixi@v0.9.1
        with:
          pixi-version: v0.50.2
          locked: true
          cache: false
          environments: pdev  # Don't use pdoc here to keep pixi Github cache small

      - name: Build Docs
        run: SPHINXOPTS="--fail-on-warning --keep-going" pixi run -e pdev make-html

      - name: deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}
