name: Lint Python Code Base

on:
  push:
    branches-ignore:
      - 'gh-pages'
    paths:
      - scraper/**
      - pyproject.toml
      - .github/workflows/lint-python.yml
  pull_request:
    paths:
      - scraper/**
      - pyproject.toml
      - .github/workflows/lint-python.yml

jobs:
  lint:
    name: Lint Python Code Base with Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "check"
          src: "./scraper"
      - uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
          args: "format --check"
          src: "./scraper"
