name: pytests-postgres

on: pull_request

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        fetch-depth: 1
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        channels: conda-forge,defaults
        python-version: ${{ matrix.python-version }}
        miniconda-version: "latest"
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        python -m pip install psycopg2-binary
        python -m pip install boto3
        python -m pip install pytest
        python -m pip install pytest-mock
        python -m pip install pytest-cov
        python -m pip install .
    - name: Run pytest for postgres
      shell: bash -l {0}
      run: |
        python -m pytest --ignore=tests/ords --ignore=tests/utilities --ignore=tests/web -v --disable-warnings

